Modelo de coleta em golang mpro
dadosjusbr/parser-mpro pull request #1
Opened 2021-04-22 18:34 UTC by thyagopereira

- Iniciando os estudos de Golang com o coletor relativo ao estado de Rondônia.

2021-04-23 11:53 UTC, danielfireman requested changes
Muito bacana a ideia de ter um modelo para iniciar um coletor em Go!

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +    month, ok := os.LookupEnv("MONTH")
Você pode usar https://github.com/kelseyhightower/envconfig e fazer esse modelo ainda mais simples.

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +        fmt.Fprintln(os.Stderr, "Invalid arguments, missing environment variable: 'MONTH'.\n")
usar a lib status, exemplo https://github.com/dadosjusbr/coletores/blob/master/trt13/main.go#L23

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +            fmt.Fprintln(os.Stderr, "As master Yoda would say: 'one must not crawl/parser th future %s/%s'.\n", month, year)
Essa situação também deve quebrar

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +    file_names := Crawl(month, year, output_path)
fileNames (go usa o padrão camel case)

2021-04-23 11:53 UTC, danielfireman commented on src/parser.go
> +	return employees
```suggestion
	return []coletores.Employee{}
```

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +
Linhas sobrando abaixo

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +    result, err := json.MarshalIndent(cr, "", "  ")
Esse código não está formatado. Por favor, ajustar sua IDE para formatar automaticamente o código toda vez que salvar

2021-04-23 11:53 UTC, danielfireman commented on src/main.go
> +    year_check, err := strconv.Atoi(year)
Como disse abaixo, go usa camel case: `yearCheck`

2021-04-23 11:53 UTC, danielfireman commented on src/crawler.go
> +	return paths
```suggestion
	return []string{}
```

2021-04-23 12:16 UTC, danielfireman commented
cc/ @cuducos

2021-04-23 12:36 UTC, cuducos commented on src/main.go
> +    "encoding/json";
A gente precisa desses `;` no final das linhas? O padrão no Go tb é ordenado alfabeticamente, não?

```suggestion
    "encoding/json"
    "fmt"
    "strconv"
    "time"
    "os"
```

2021-04-23 12:36 UTC, cuducos commented on src/main.go
> +    if err == nil{
Não fica mais legível sair se `err != nil` e manter um [_flat success path_](https://www.vinta.com.br/blog/2018/flat-success-path/)?

2021-04-23 12:36 UTC, cuducos commented on src/main.go
> +            AgencyID:  "mppe",
Pq `"mppe"` aqui se o código fica em `src/` e o PR diz MP-RO? Fiquei confuso…

2021-04-23 18:10 UTC, thyagopereira commented on src/main.go
> +            AgencyID:  "mppe",
Foi falha minha. Peço desculpa. Este campo deve ser preenchido com "mpro".

2021-04-24 17:38 UTC, danielfireman approved these changes

2021-04-24 17:38 UTC, danielfireman commented on src/main.go
> +	Month        int
Recomendo que use mais o poder dessa lib. Através de [struct tags](https://github.com/kelseyhightower/envconfig#struct-tag-support) você pode descrever os nomes das variáveis (em maiúsculas e separadas por `_`). Através desse recurso você também pode marcar campos como requeridos (mes e ano, por exemplo) e setar valores padrão (output folder)

2021-04-24 17:38 UTC, danielfireman commented on src/parser.go
> +func Parse(file_names []string, month int, year int) []coletores.Employee {
fileNames

2021-04-24 17:38 UTC, danielfireman commented on src/crawler.go
> +func Crawl(month int, year int, output_path string) []string {
outputPath

2021-04-24 17:38 UTC, danielfireman commented on src/parser.go
> +func Parse(file_names []string, month int, year int) []coletores.Employee {
Mantenha a mesma o mês e o ano primeiro, assim concorda mais com a função `Craw`

2021-04-24 17:38 UTC, danielfireman commented on src/main.go
> +	currentYear, currentMonth, _ := time.Now().Date()
Sugestão para simplificar as comparações abaixo. A API `time` permite descrever o que você quer quase em inglês

```go
  now := time.Now()
  currData := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, now.Location())
  crawlDate := time.Date(year, month, 1, 0, 0, 0, 0, now.Location())
  if crawlDate.Afer(currData) {
```

2021-04-26 17:05 UTC, merged